### PR TITLE
Clean up grunt and add null-terminated string reading

### PR DESCRIPTION
**Pull request by joshperry**

### CODE REVIEW

**Comment by joshperry** [comment]
@villadora I wonder if you could apply this PR and push to npm or if you're not interested in maintaining this anymore, I would be happy to. I really don't want to fork and have a different name on npm, `buffer-reader` is a really great name and a great counterpart to `buffer-writer`.

Josh

**Comment by villadora** [comment]
Hi joshperry, I may don't have much time working this recently. It's so glad you can do more improvements on this~

**Comment by villadora** [comment]
v0.1.0 released.

**Comment by villadora** [comment]
If you want to do more changes on this module, may I have you npm user id? so I could add you to the package.

**Comment by villadora** [comment]
If you want to do more changes on this module, may I have you npm user id? so I could add you to the package.

**Comment by villadora** [comment]
If you want to do more changes on this module, may I have you npm user id? so I could add you to the package.

**Comment by joshperry** [comment]
@villadora That would be great, my npm username is `joshperry`. Thanks for merging this!

**Comment by villadora** [comment]
@joshperry I just get you added in npm, so you can do changes and publish.

**Pull request merged**
